CHANGELOG.md, pyproject.toml, src/firewheel/__init__.py, src/firewheel/cli/firewheel_cli.py, src/firewheel/lib/grpc/firewheel_grpc_server.py, src/firewheel/tests/unit/cli/test_cli.py
This PR moves away from manually defined versioning to using [setuptools-scm](https://setuptools-scm.readthedocs.io/en/latest/) and our GitHub releases to version the software.
=> Using built-in tools to automatically version FIREWHEEL

README.rst
> The [Open Source Security Foundation (OpenSSF)](https://openssf.org/) Best Practices badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice. The OpenSSF Best Practices Badge is inspired by the many badges available to projects on GitHub. Consumers of the badge can quickly assess which FLOSS projects are following best practices and as a result are more likely to produce higher-quality secure software.
This PR completed the initial assessment for FIREWHEEL and adds the corresponding badge.
=> Adding a badge for the Open Source Security Foundation (OpenSSF) Best Practices

.gitlab-ci.yml, renovate.json
This PR removes more dead code as we transition to open source. Specifically, we moved from renovate to dependabot and no longer need to clone `firewheel_repo_base` or `firewheel_repo_tutorials` as they are now open source. Lastly, we no longer need to have a deploy function as that was replaced by the corresponding GitHub action.
=> Cleaning up the gitlab CI based on newly open sourced model components

.github/workflows/linting.yml, .github/workflows/python-publish.yml
This adds the `workflow_call` keyword to the current workflows, enabling the workflows to be used as [reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows). This will allow us to essentially import the standard FIREWHEEL workflows in our model component repositories (see sandialabs/firewheel_repo_base#1).
=> Allow workflow reuse across the FIREWHEEL ecosystem

.github/workflows/python-publish.yml
This allows model component repositories to pass their own PYPI secret to the package publishing workflow.
=> Enabling the passing of the PYPI token to this workflow

.github/workflows/documentation.yml, docs/source/conf.py, tox.ini
This PR adds the newly released documentation for officially supported model components and enables previewing the documentation prior to merging as we now always build the docs, but will only release them when the PR has been merged.
As of this PR the documentation includes:
* [firewheel_repo_base](https://github.com/sandialabs/firewheel_repo_base)
* [firewheel_repo_tutorials](https://github.com/sandialabs/firewheel_repo_tutorials)
* [firewheel_repo_ntp](https://github.com/sandialabs/firewheel_repo_ntp)
* [firewheel_repo_linux](https://github.com/sandialabs/firewheel_repo_linux)
* [firewheel_repo_vyos](https://github.com/sandialabs/firewheel_repo_vyos)
* [firewheel_repo_layer2](https://github.com/sandialabs/firewheel_repo_layer2)
* …
=> Adding the model component documentation once it becomes available.

docs/source/conf.py, docs/source/system/architecture.rst, src/firewheel/__init__.py
This PR updates the documentation to fix an outdated comment that Elasticsearch is installed with FIREWHEEL. Additionally, we fix a bug introduced by #14 which neglected to update the version for the Sphinx documentation.
=> Removing outdated references to Elasticsearch

.github/actions/prepare-discovery/action.yml, .github/actions/prepare-firewheel/action.yml, .github/actions/prepare-minimega/action.yml, .github/actions/prepare-tox/action.yml, .github/workflows/documentation.yml, .github/workflows/linting.yml, .github/workflows/testing.yml, pyproject.toml, src/firewheel/cli/firewheel_cli.py, src/firewheel/cli/helpers/test/unit, src/firewheel/cli/init_firewheel.py, src/firewheel/cli/utils.py, src/firewheel/tests/conftest.py, src/firewheel/tests/unit/cli/test_cli_completion.py, src/firewheel/tests/unit/conftest.py, src/firewheel/tests/unit/control/test_performance.py, tox.ini
This provides a starting point for converting our GitLab CI testing infrastructure to the GitHub Actions workflow. 
To avoid duplication in the workflow scripts, I've created a new set of [composite actions](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action) to install minimega, discovery, FIREWHEEL, and tox. We should hopefully be able to use these composite actions to dramatically simplify some of the CI scripts we had before. I've also upgraded the versions of referenced reusable versions where possible.
The unit tests have been upgraded to provide increased utility and work better through the FIREWHEEL interface:
- Running the `firewheel test unit` helper now returns the appropriate exit code returned by pytest, which was previously …
=> Provide CI testing support

docs/source/install/install.rst, docs/source/install/prereqs.rst, docs/source/install/prereqs/dependencies.rst
This provides a few minor updates to the docs.
1. I clarify that the `PYTHON_BIN` environment variable is the executable (which may be either a path or a symlink). I think this wording might be better, because just giving `python3` (assuming that it's being run in a virtual environment) doesn't strike me as a path.
2. It appears that `libenchant-dev` has been superseded by `libenchant-2-dev` and is accessible with that new name in the relevant Ubuntu repositories. (Similar for Fedora-based OSs and `enchant2-devel` and `enchant-devel`.)
=> Update documentation with minor changes

.github/dependabot.yml, .github/release-drafter.yml, .github/workflows/pr-title-checker.yaml, .github/workflows/release-drafter.yml, .github/workflows/update-changelog.yaml, CHANGELOG.md, CONTRIBUTING.rst
This PR is an effort to improve the OSS development process for FIREWHEEL. In it, we add the following GitHub actions:
-  [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) - Validate that PR titles have the general style of [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). We have also extended the default list to add a few new commit "types".
- [release-drafter/release-drafter](https://github.com/release-drafter/release-drafter) - Drafts the next release notes as pull requests are merged into main. 
- This action also includes an "autolabeler" which checks the branch name and PR title to automatically add a label to the request.
- [danielchabr/pr-labels-checker](https://github.com/danielchabr/pr-labels-checker) - Github …
=> ci: Add new CI actions to autotag PRs and update release notes and changelog entries

.github/workflows/documentation.yml, .github/workflows/linting.yml, .github/workflows/testing.yml, CONTRIBUTING.rst
CI pipelines for model component repos currently cannot access the composite actions that are called in the reusable workflows for this repo. It seems that this is because [GitHub actions defined in a called repo](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#overview) (e.g., `sandialabs/firewheel`) are executed as if they were defined in the caller repo (e.g., the MC repo).
An example of this failing behavior can be [found in the recent CI pipeline](https://github.com/sandialabs/firewheel_repo_dns/actions/runs/13420030343/job/37490153500#step:4:1) for the `firewheel_repo_dns` repo. That repo cannot find `.github/actions/prepare-tox` because it's looking for it in the `sandialabs/firewheel_repo_dns` repository rather than `sandialabs/firewheel` where it actually …
=> ci: Enhance CI reusability

src/firewheel/cli/ssh_manager.py, src/firewheel/tests/unit/cli/test_ssh_manager.py
@gregjacobus was running into an issue where the SSH manager would fail to execute a `grep` command when it was passed via the command line. It appears that the issue stemmed from a failure to use `shlex` when recombining arguments parsed from the command line.
This updates the SSH manager to ensure that `shlex` is used for all parsing and recombining operations when manipulating arguments passed to as commands to the SSH/SCP commands. 
The PR also adds a few extra test cases to have better coverage of quoted commands.
=> fix: Correct behavior of the SSH Manager for quoted strings

src/firewheel/cli/completion/completion-template.sh
This PR enables shells that do not have `source` or the ability to use `[[` such as `/bin/sh`. Closes #67.
=> fix: Making adjustments to the tab completion to work with `/bin/sh`

.github/workflows/linting.yml, .github/workflows/pr-title-checker.yaml, .github/workflows/release-drafter.yml, .github/workflows/testing.yml, .github/workflows/update-changelog.yaml
This set of changes should enable a more secure CI pipeline (e.g., avoiding supply chain attacks) while still maintaining the current functionality. I suspect that the pipeline will still fail prior to merge due to some of the restrictions. Any issues after that can be addressed quickly.
=> ci: Updating CI to use specific tagged versions of github actions and minimizing/enforcing permissions for all actions.

README.rst
This adds a new reference to  the paper for https://github.com/ORNL/cyberwheel.
=> doc: Adding a reference to Cyberwheel

.github/workflows/docker.yml, .github/workflows/release-drafter.yml
In addition to fixing the CI pipeline for label checking, this PR and stops building docker containers for all branches and only does so for pushes to main or a new release.
=> ci: fixing an issue where checking for labels fails

.github/workflows/release-drafter.yml
This is intended to only run the PR label checker for events occuring in a pull request context (cases where the `event_name` is `pull_request_target` and not pushes).
=> ci: Run PR label check only in pull request contexts

tox.ini
This PR fixes the pipeline, currently broken after an update to pydocstyle. We did not previously pin a pydocstyle version in [`tox.ini`](https://github.com/sandialabs/firewheel/blob/986cb66cbfcd2d6adadbb1fa19b9eced838462aa/tox.ini#L38).
A new command line option ([`--ignore-private-args`](https://jsh9.github.io/pydoclint/config_options.html#14---ignore-private-args-shortform--ipa-default-false)) was [added in pydocstyle 0.6.3](https://github.com/jsh9/pydoclint/blob/main/CHANGELOG.md#063---2025-03-30). The default value of that argument—which I believe we should be defaulting to—is `False` (e.g., _do not_ ignore private arguments); however, it seems like even though we are specifying private arguments in our docstrings, the check is still failing.
This PR does not solve the problem or …
=> ci: Fix pydocstyle version to prevent linting errors

src/firewheel/tests/unit/control/test_repository_db.py
The `add_repository_invalid` test can fail on systems where the user has read permissions to the `/root` directory. (This is likely uncommon, but not infeasible.) 
This adds a mocking function to simulate the `os.access` function such that it _always_ returns `False` for the `/root` directory. I figure this is preferable than trying to find a file that will not be user-readable on every system, especially because our unit tests have no need to test the behavior of the `os.access` function itself.
=> test: Use mock for simulating permissioned systems

docs/source/install/install.rst, install.sh
This captures a handful of the higher priority elements introduced by #91, while focusing on backwards compatibility. 
The primary modification here is to make more clear the distinction between cloned/uncloned editable/non-editable installs and have the docs adequately reflect the actions in the `install.sh` script. Previously, the documentation stated that the installer would clone our default model components, which was true before we transitioned to the package model. As we've made that transition, some of the implied functionality has been lost—right now, running the install script with no arguments will clone MCs but not install them... so still technically accurate, but somewhat misleading because we do not mention that any further actions to be taken. In a similar way, calling the …
=> fix: Clearly delineate between editable/non-editable MC installs

install.sh, pyproject.toml, tox.ini
[Setuptools 77 ](https://github.com/pypa/setuptools/blob/12ca0186ba7d9bf387d65400bb05205d0bcf9e56/NEWS.rst#v7700) added license expression ([PEP 639](https://peps.python.org/pep-0639/#add-license-expression-field)) support. However, this breaks the current method of how setuptools checks for the license (see https://github.com/pypa/setuptools/issues/4903). While upgrading is ideal, given our continued support for Python 3.8, we must instead lock in the version of setuptools. Additionally, this PR locks in several other packages to address similar deprecation and Python 3.8 issues. 
Lastly, this PR addresses some circular dependency challenges which occurred when installing firewheel[dev]. These changes should fix (and stablize) our CI pipeline as well.
=> chore: Tightening dependencies to address python 3.8 support

docs/source/cli/commands.rst, docs/source/cli/helper_docs.rst, src/firewheel/cli/configure_firewheel.py, src/firewheel/tests/unit/cli/test_cli_configure.py
This PR adds a new command which enables users to easily edit the FIREWHEEL configuration. The `firewheel config edit` command will automatically use the `VISUAL` or `EDITOR` environment variables. Alternatively, users can pass in their own editor of choice (or override the environment variables). This PR also updates the associated documentation.
=> feat(cli): Adding a new firewheel config edit command

install.sh
I didn't notice this on #127, but pre-commit and tox are installed by the `dev` extra. Because of that, it is redundant for us to install them before running our local flavor of `pip install firewheel[dev]` in the install script.
=> chore: Remove duplicate pip installation instruction

src/firewheel/cli/helpers/start, src/firewheel/cli/helpers/stop/hard, src/firewheel/cli/helpers/stop/index, src/firewheel/lib/minimega/api.py
This fixes FIREWHEEL working in a cluster. There are a few places where the minimega namespace was hard-coded.
I cannot figure out why this change is necessary now, but everything seemed to work in the past. Doesn't seem like the minimega API changed at all. Not sure it's necessarily important, but would love to know if anybody has comments.
TODO:
=> fix: Fixing namespaces

docker/firewheel.dockerfile, docker/fsroot/usr/local/bin/entry
This PR makes the following adjustments to the Docker container:
* Corrects the path to Discovery
* Includes an additional minimega environment variable (`MM_LOGFILE`)
* Removes hardcoded paths with the respective environment variable
* Creates expected paths for log files
* Updates the `firewheel config`  with any minimega environment variables
=> fix: Expand docker variables and fix discovery path

src/firewheel/cli/helpers/repository/install
This PR fixes an issue where if one MC fails to install for a repository, the entire repository stops installing. This causes issues where a user may only need a subset of the repository installed.
=> fix: Address repository installation short circuit

src/firewheel/cli/configure_firewheel.py, src/firewheel/tests/unit/cli/test_cli_configure.py
This adds a CLI command for getting the path to the FIREWHEEL configuration file.
Example: 
```bash
firewheel config path
> /opt/firewheel/src/firewheel/firewheel.yaml
```
=> feat: Add a CLI command for getting the configuration path

install.sh
This removes the call to build a FIREWHEEL package source distribution from the install script. This should no longer be necessary now that FIREWHEEL is either installed directly from PyPI or via an editable install.
For applications where building a source distribution is necessary (e.g., publishing to PyPI), that process should be handled elsewhere—such as in CI job or in a local build workflow.
=> chore: Remove code for building wheel in favor of CI deployments

.gitlab-ci.yml
This adds flexibility to the GitLab CI script.
First, it adds a new rule to the performance testing, allowing a GitLab CI/CD environment variable to be used for determining whether or not performance tests should be run. The `FIREHWEEL_TEST_PERFORMANCE` variable can be set to `true` for GitLab instances where performance tests should be run. It can be set to `false` for GitLab instances where performance tests are not desired.
Second, it uses a GitLab CI/CD variable for defining the tags of GitLab runners that should run performance tests. This was previously hardcoded `ubuntu2204`, but it could conceivably be named differently.
Please select the type of change your pull request introduces:
=> ci: Add flexibility to GitLab CI
